### ISSUE TITLE
SNMP module not visible in Companion

### ISSUE THREAD

**Issue by JonathanPowe** [bitfocus/companion-module-generic-snmp#1]
Thank you for creating this module. 
It doesn't seem to be visible in the modules list in Companion. I've checked the latest beta builds and searched for "SNMP", but can't find it.
Do I need to change a setting in Companion to be able to use this module?
Or is it still awaiting approval before being added to the main builds?
![image](https://user-images.githubusercontent.com/101350871/163969983-a71954a5-1702-4df3-b3ed-db251c9ea5f3.png)

**Comment by Julusian** [comment]
@estilles what is the status of this? should it be pulled into the beta builds?
